server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.apache.hive.jdbc.HiveDriver
    url: jdbc:hive2://192.168.2.2:10000/flights?characterEncoding=utf-8
    username: hadoop
    data-password: 123


